### PR TITLE
Update syn, quote and bump version

### PR DESCRIPTION
**Pull request by Eijebong**

### CODE REVIEW

**Comment by Eijebong** [comment]
Ping ? :)

**Comment by Eijebong** [comment]
@upsuper

**Comment by upsuper** [comment]
Ah, sorry for the delay. I somehow didn't watch my own project, and I have no idea why...

**Comment by upsuper** [comment]
You also need to bump the version of macro in the root Cargo.toml, otherwise the build will fail.

I fixed this in 8be960d8cff4148de64f5cb21544793d6dd180ae so close this PR.

Thanks!

**Pull request closed without merging**
